repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: ["--fix", "--line-length=125"]
      - id: ruff-format
        args: ["--line-length=125"]

  - repo: local
    hooks:
      - id: check-py-file-length
        name: Check Python file length (<= 500 lines)
        entry: python scripts/check_file_length.py --max-lines 500 --paths src tests
        language: system
        pass_filenames: false

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--line-length=125"]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args:
          - --config-file=pyproject.toml
          - --cache-dir=.mypy_cache
          - --show-error-codes
          - --no-error-summary
        # Only run on changed files for faster pre-commit
        pass_filenames: true
        # Only check source files, not tests (tests are excluded in pyproject.toml)
        files: ^src/

  - repo: local
    hooks:
      - id: pytest
        name: Run test suite
        entry: pytest tests/ -v
        language: system
        pass_filenames: false
        stages: [pre-push]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.19
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-frontmatter

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.14.0
    hooks:
      - id: markdownlint-cli2
      
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["--config", ".codespellrc"]

