name: Publish to PyPI

on:
  release:
    types: [created]

# Set minimal permissions for the workflow
permissions:
  contents: read

jobs:
  publish:
    name: Publish PDF2Foundry to PyPI
    runs-on: ubuntu-latest
    environment:
      name: ${{ vars.PYPI_ENVIRONMENT || 'pypi-publish' }}
      url: https://pypi.org/p/pdf2foundry
    permissions:
      id-token: write  # Required for trusted publishing
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Set up Node.js (for Foundry CLI)
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          
      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils
          tesseract --version
          
      - name: Install Node.js dependencies
        run: |
          npm install
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          
      - name: Verify package can be installed
        run: |
          pip install -e ".[dev]"
          pdf2foundry --help
          
      - name: Run tests to ensure package integrity
        run: |
          pytest tests/unit/ --cov=pdf2foundry --cov-report=term-missing
          
      - name: Build package
        run: |
          python -m build
          
      - name: Check package with twine
        run: |
          twine check dist/*
          
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          
      - name: Verify published package
        run: |
          # Wait a bit for PyPI to update
          sleep 30
          # Extract version from git tag (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Verifying version: $VERSION"
          # Try to install the published package
          pip install --upgrade --force-reinstall pdf2foundry==$VERSION
          pdf2foundry --help
